/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Run
         * @description The Live tab's day picker: replay any cached day with the full fleet.
         */
        post: operations["start_run_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Latest Run */
        get: operations["get_latest_run_runs_latest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Results */
        get: operations["get_results_runs__run_id__results_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/ledger": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Ledger
         * @description The Command Ledger per Market Interval: issued / acked / expired / failed.
         */
        get: operations["get_ledger_runs__run_id__ledger_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream Events */
        get: operations["stream_events_runs__run_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/marketdata/days": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Cached Days */
        get: operations["get_cached_days_marketdata_days_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/marketdata/prices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Prices */
        get: operations["get_prices_marketdata_prices_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chaos/apply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Apply Chaos */
        post: operations["apply_chaos_chaos_apply_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chaos/clear": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Clear Chaos */
        post: operations["clear_chaos_chaos_clear_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/chaos-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Chaos Events */
        get: operations["get_chaos_events_runs__run_id__chaos_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/slo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Slo */
        get: operations["get_slo_runs__run_id__slo_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/insights/backtest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Backtest */
        get: operations["get_backtest_insights_backtest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/insights/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Insights */
        get: operations["get_insights_insights_report_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/risk/day": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Risk Day */
        get: operations["get_risk_day_risk_day_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/risk/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Risk Report */
        get: operations["get_risk_report_risk_report_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApplyChaosRequest */
        ApplyChaosRequest: {
            /**
             * Scenario
             * @enum {string}
             */
            scenario: "worker-kill" | "duplicate-commands" | "partition" | "telemetry-delay" | "feed-outage" | "feed-outlier";
            /** Run Id */
            run_id: string;
            /** Target */
            target?: string | null;
            /** Duration S */
            duration_s?: number | null;
            /** Pct */
            pct?: number | null;
            /** Delay S */
            delay_s?: number | null;
        };
        /** BacktestReport */
        BacktestReport: {
            /** Settlement Point */
            settlement_point: string;
            /** Start Day */
            start_day: string | null;
            /** End Day */
            end_day: string | null;
            /** Fleet Mw */
            fleet_mw: number;
            /** Fleet Mwh */
            fleet_mwh: number;
            /** Start Soc Pct */
            start_soc_pct: number;
            /** Degradation Usd Per Mwh */
            degradation_usd_per_mwh: number;
            /** Naive Discharge Threshold Usd */
            naive_discharge_threshold_usd: number;
            /** Naive Charge Threshold Usd */
            naive_charge_threshold_usd: number;
            /** Lp Solve Ms P50 */
            lp_solve_ms_p50: number;
            /** Lp Solve Ms Max */
            lp_solve_ms_max: number;
            /** Summary */
            summary: components["schemas"]["StrategySummary"][];
            /** Days */
            days: components["schemas"]["DayResult"][];
        };
        /** CachedDay */
        CachedDay: {
            /**
             * Day
             * Format: date
             */
            day: string;
            /** Max Rt Price Usd Per Mwh */
            max_rt_price_usd_per_mwh: number;
        };
        /** CalibrationBin */
        CalibrationBin: {
            /** Lo */
            lo: number;
            /** Hi */
            hi: number;
            /** Count */
            count: number;
            /** Mean Predicted */
            mean_predicted: number;
            /** Observed Rate */
            observed_rate: number;
        };
        /**
         * ChaosEvent
         * @description One row of the chaos event log: when, which scenario, against what.
         */
        ChaosEvent: {
            /** Run Id */
            run_id: string;
            /**
             * At
             * Format: date-time
             */
            at: string;
            /** Scenario */
            scenario: string;
            /**
             * Action
             * @enum {string}
             */
            action: "apply" | "clear";
            /** Target */
            target: string;
            /** Interval Start */
            interval_start?: string | null;
            /**
             * Detail
             * @default
             */
            detail: string;
        };
        /** ClearChaosRequest */
        ClearChaosRequest: {
            /**
             * Scenario
             * @enum {string}
             */
            scenario: "worker-kill" | "duplicate-commands" | "partition" | "telemetry-delay" | "feed-outage" | "feed-outlier";
            /** Run Id */
            run_id: string;
            /**
             * Target
             * @default simulators
             */
            target: string;
        };
        /** Concentration */
        Concentration: {
            /** Regime */
            regime: string;
            /** Intervals */
            intervals: number;
            /** Days */
            days: number;
            /** Total Opportunity Usd */
            total_opportunity_usd: number;
            /** Top Intervals */
            top_intervals: components["schemas"]["TopShare"][];
            /** Top Days Share Pct */
            top_days_share_pct: number;
            /** Top Days */
            top_days: components["schemas"]["TopDay"][];
            /** Curve */
            curve: components["schemas"]["CurvePoint"][];
        };
        /** CurvePoint */
        CurvePoint: {
            /** Intervals Pct */
            intervals_pct: number;
            /** Value Pct */
            value_pct: number;
        };
        /** DayResult */
        DayResult: {
            /**
             * Day
             * Format: date
             */
            day: string;
            /** Strategy */
            strategy: string;
            /** Value Usd */
            value_usd: number;
            /** Usd Per Mw Month */
            usd_per_mw_month: number;
            /** Discharged Mwh */
            discharged_mwh: number;
            /** Charged Mwh */
            charged_mwh: number;
            /** Intervals */
            intervals: number;
            /** Forecast Source */
            forecast_source: string;
        };
        /** DependencyStatus */
        DependencyStatus: {
            /** Name */
            name: string;
            /** Ok */
            ok: boolean;
            /**
             * Detail
             * @default
             */
            detail: string;
        };
        /** DowntimeCell */
        DowntimeCell: {
            /** Month */
            month: string;
            /** Hour */
            hour: number;
            /** Intervals */
            intervals: number;
            /** Mean Usd Per Min */
            mean_usd_per_min: number;
            /** P95 Usd Per Min */
            p95_usd_per_min: number;
        };
        /** FoldResult */
        FoldResult: {
            /** Test Month */
            test_month: string;
            /** Provenance */
            provenance: string;
            /** Train Rows */
            train_rows: number;
            /** Test Rows */
            test_rows: number;
            /** Threshold Usd Per Mwh */
            threshold_usd_per_mwh: number;
            /** Spike Premium Usd Per Mwh */
            spike_premium_usd_per_mwh: number;
            /** Test Positive Rate */
            test_positive_rate: number;
            model: components["schemas"]["ScoreCard"];
            climatology: components["schemas"]["ScoreCard"];
        };
        /** ForecastError */
        ForecastError: {
            /** Available */
            available: boolean;
            /** Reason */
            reason: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Headline */
        Headline: {
            /** Top1 Share Pct */
            top1_share_pct: number;
            /** Top5 Share Pct */
            top5_share_pct: number;
            /** Top10 Days Share Pct */
            top10_days_share_pct: number;
            /** Peak Month */
            peak_month: string;
            /** Peak Hour */
            peak_hour: number;
            /** Peak Mean Usd Per Min */
            peak_mean_usd_per_min: number;
            /** Peak P95 Usd Per Min */
            peak_p95_usd_per_min: number;
            /** Text */
            text: string;
        };
        /** HealthResponse */
        HealthResponse: {
            /** Ok */
            ok: boolean;
            /** Dependencies */
            dependencies: components["schemas"]["DependencyStatus"][];
            /** Services */
            services: components["schemas"]["ServiceCount"][];
        };
        /** InsightsReport */
        InsightsReport: {
            /** Settlement Point */
            settlement_point: string;
            /** Device Count */
            device_count: number;
            /** Fleet Mw */
            fleet_mw: number;
            /** Start Day */
            start_day: string | null;
            /** End Day */
            end_day: string | null;
            headline: components["schemas"]["Headline"] | null;
            /** Concentration */
            concentration: components["schemas"]["Concentration"][];
            /** Downtime */
            downtime: components["schemas"]["DowntimeCell"][];
            forecast_error: components["schemas"]["ForecastError"];
        };
        /** IntervalResult */
        IntervalResult: {
            /** Run Id */
            run_id: string;
            /**
             * Interval Start
             * Format: date-time
             */
            interval_start: string;
            /** Settlement Point */
            settlement_point: string;
            /** Price Usd Per Mwh */
            price_usd_per_mwh: number;
            /** Target Mw */
            target_mw: number;
            /** Achievable Mw */
            achievable_mw: number;
            /** Delivered Mw */
            delivered_mw: number;
            /** Level */
            level: string;
            /** Dispatched Count */
            dispatched_count: number;
            /** Acked Count */
            acked_count: number;
            /** Reserve Violations */
            reserve_violations: number;
            /** Latency Ms */
            latency_ms: number;
            /**
             * Budget Ms
             * @default 0
             */
            budget_ms: number;
            /**
             * Online Devices
             * @default 0
             */
            online_devices: number;
            /**
             * Shard Count
             * @default 0
             */
            shard_count: number;
            /**
             * Soc P10 Pct
             * @default 0
             */
            soc_p10_pct: number;
            /**
             * Soc P50 Pct
             * @default 0
             */
            soc_p50_pct: number;
            /**
             * Soc P90 Pct
             * @default 0
             */
            soc_p90_pct: number;
            /**
             * Duplicate Deliveries
             * @default 0
             */
            duplicate_deliveries: number;
            /**
             * Duplicate Effects
             * @default 0
             */
            duplicate_effects: number;
            /**
             * Retried Dispatches
             * @default 0
             */
            retried_dispatches: number;
            /**
             * Planned Achievable Mw
             * @default 0
             */
            planned_achievable_mw: number;
            /**
             * Stale Devices
             * @default 0
             */
            stale_devices: number;
            /**
             * Unresponsive Devices
             * @default 0
             */
            unresponsive_devices: number;
            /**
             * Reallocation Rounds
             * @default 0
             */
            reallocation_rounds: number;
            /**
             * Reallocated Mw
             * @default 0
             */
            reallocated_mw: number;
            /**
             * Reallocated Devices
             * @default 0
             */
            reallocated_devices: number;
            /**
             * Feed Status
             * @default ok
             */
            feed_status: string;
            /**
             * Feed Detail
             * @default
             */
            feed_detail: string;
            /**
             * Strategy
             * @default
             */
            strategy: string;
            /**
             * Forecast Source
             * @default
             */
            forecast_source: string;
            /**
             * Plan Mw
             * @default []
             */
            plan_mw: number[];
        };
        /** LatestRun */
        LatestRun: {
            /** Run Id */
            run_id: string | null;
        };
        /**
         * LedgerIntervalSummary
         * @description The Command Ledger for one Market Interval: every Command issued, by status.
         */
        LedgerIntervalSummary: {
            /**
             * Interval Start
             * Format: date-time
             */
            interval_start: string;
            /** Issued */
            issued: number;
            /** Acked */
            acked: number;
            /** Expired */
            expired: number;
            /** Failed */
            failed: number;
            /** Unacked */
            unacked: number;
            /** Delivered Mw */
            delivered_mw: number;
        };
        /** PricePoint */
        PricePoint: {
            /**
             * Interval Start
             * Format: date-time
             */
            interval_start: string;
            /** Rt Price Usd Per Mwh */
            rt_price_usd_per_mwh: number | null;
            /** Dam Price Usd Per Mwh */
            dam_price_usd_per_mwh: number | null;
        };
        /** RecoveryTime */
        RecoveryTime: {
            /**
             * At
             * Format: date-time
             */
            at: string;
            /** Scenario */
            scenario: string;
            /** Target */
            target: string;
            /**
             * Interval Start
             * Format: date-time
             */
            interval_start: string;
            /** Recovery S */
            recovery_s: number | null;
        };
        /** RiskDay */
        RiskDay: {
            /**
             * Day
             * Format: date
             */
            day: string;
            /** Settlement Point */
            settlement_point: string;
            /** Threshold Usd Per Mwh */
            threshold_usd_per_mwh: number;
            /** Provenance */
            provenance: string;
            /** Points */
            points: components["schemas"]["RiskPoint"][];
        };
        /** RiskPoint */
        RiskPoint: {
            /**
             * Interval Start
             * Format: date-time
             */
            interval_start: string;
            /** Rt Price Usd Per Mwh */
            rt_price_usd_per_mwh: number | null;
            /** Spike */
            spike: boolean;
            /** P Spike 1H Ahead */
            p_spike_1h_ahead: number | null;
            /** Curve */
            curve: number[];
        };
        /** RiskReport */
        RiskReport: {
            /** Settlement Point */
            settlement_point: string;
            /**
             * Start Day
             * Format: date
             */
            start_day: string;
            /**
             * End Day
             * Format: date
             */
            end_day: string;
            /** Seed */
            seed: number;
            /** Quantile */
            quantile: number;
            /** Horizon Intervals */
            horizon_intervals: number;
            /** Features */
            features: string[];
            /** Missing Inputs */
            missing_inputs: string[];
            /** Threshold Usd Per Mwh */
            threshold_usd_per_mwh: number;
            /** Folds */
            folds: components["schemas"]["FoldResult"][];
            /** Walk Forward Rows */
            walk_forward_rows: number;
            /** Walk Forward Positive Rate */
            walk_forward_positive_rate: number;
            model: components["schemas"]["ScoreCard"];
            climatology: components["schemas"]["ScoreCard"];
            /** Brier Skill Vs Climatology */
            brier_skill_vs_climatology: number;
            /** Predictions Sha256 */
            predictions_sha256: string;
        };
        /**
         * ScoreCard
         * @description One predictor (model or climatology) scored on one set of test rows.
         */
        ScoreCard: {
            /** Brier */
            brier: number;
            /** Pr Auc */
            pr_auc: number | null;
            /** Calibration */
            calibration: components["schemas"]["CalibrationBin"][];
        };
        /** ServiceCount */
        ServiceCount: {
            /** Name */
            name: string;
            /** Ready */
            ready: number;
            /** Total */
            total: number;
        };
        /** SloReport */
        SloReport: {
            /** Run Id */
            run_id: string;
            /** Rows */
            rows: components["schemas"]["SloRow"][];
            /** Recoveries */
            recoveries: components["schemas"]["RecoveryTime"][];
        };
        /** SloRow */
        SloRow: {
            /** Name */
            name: string;
            /** Target */
            target: string;
            /** Actual */
            actual: string;
            /** Ok */
            ok: boolean;
        };
        /** StartRunRequest */
        StartRunRequest: {
            /** Day */
            day?: string | null;
            /** Settlement Point */
            settlement_point?: string | null;
            /** Strategy */
            strategy?: ("naive" | "lp" | "lp_risk") | null;
        };
        /** StartedRun */
        StartedRun: {
            /** Run Id */
            run_id: string;
        };
        /** StrategySummary */
        StrategySummary: {
            /** Strategy */
            strategy: string;
            /** Days */
            days: number;
            /** Value Usd */
            value_usd: number;
            /** Usd Per Mw Month */
            usd_per_mw_month: number;
            /** Discharged Mwh */
            discharged_mwh: number;
            /** Share Of Perfect Foresight Pct */
            share_of_perfect_foresight_pct: number;
        };
        /** TopDay */
        TopDay: {
            /**
             * Day
             * Format: date
             */
            day: string;
            /** Opportunity Usd */
            opportunity_usd: number;
            /** Share Pct */
            share_pct: number;
        };
        /** TopShare */
        TopShare: {
            /** Top Pct */
            top_pct: number;
            /** Intervals */
            intervals: number;
            /** Share Pct */
            share_pct: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    start_run_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StartedRun"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_latest_run_runs_latest_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LatestRun"];
                };
            };
        };
    };
    get_results_runs__run_id__results_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntervalResult"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ledger_runs__run_id__ledger_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LedgerIntervalSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_events_runs__run_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_cached_days_marketdata_days_get: {
        parameters: {
            query?: {
                settlement_point?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CachedDay"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_prices_marketdata_prices_get: {
        parameters: {
            query: {
                day: string;
                settlement_point?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PricePoint"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    apply_chaos_chaos_apply_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplyChaosRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChaosEvent"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clear_chaos_chaos_clear_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClearChaosRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChaosEvent"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_chaos_events_runs__run_id__chaos_events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChaosEvent"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_slo_runs__run_id__slo_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SloReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_backtest_insights_backtest_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacktestReport"];
                };
            };
        };
    };
    get_insights_insights_report_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InsightsReport"];
                };
            };
        };
    };
    get_risk_day_risk_day_get: {
        parameters: {
            query: {
                day: string;
                settlement_point?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RiskDay"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_risk_report_risk_report_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RiskReport"];
                };
            };
        };
    };
}
