/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Run
         * @description The Live tab's day picker: replay any cached day with the full fleet.
         */
        post: operations["start_run_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Latest Run */
        get: operations["get_latest_run_runs_latest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Results */
        get: operations["get_results_runs__run_id__results_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/ledger": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Ledger
         * @description The Command Ledger per Market Interval: issued / acked / expired / failed.
         */
        get: operations["get_ledger_runs__run_id__ledger_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream Events */
        get: operations["stream_events_runs__run_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/marketdata/days": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Cached Days */
        get: operations["get_cached_days_marketdata_days_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/marketdata/prices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Prices */
        get: operations["get_prices_marketdata_prices_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chaos/apply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Apply Chaos */
        post: operations["apply_chaos_chaos_apply_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chaos/clear": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Clear Chaos */
        post: operations["clear_chaos_chaos_clear_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/chaos-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Chaos Events */
        get: operations["get_chaos_events_runs__run_id__chaos_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/slo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Slo */
        get: operations["get_slo_runs__run_id__slo_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApplyChaosRequest */
        ApplyChaosRequest: {
            /**
             * Scenario
             * @enum {string}
             */
            scenario: "worker-kill" | "duplicate-commands" | "partition" | "telemetry-delay";
            /** Run Id */
            run_id: string;
            /** Target */
            target?: string | null;
            /** Duration S */
            duration_s?: number | null;
            /** Pct */
            pct?: number | null;
            /** Delay S */
            delay_s?: number | null;
        };
        /** CachedDay */
        CachedDay: {
            /**
             * Day
             * Format: date
             */
            day: string;
            /** Max Rt Price Usd Per Mwh */
            max_rt_price_usd_per_mwh: number;
        };
        /**
         * ChaosEvent
         * @description One row of the chaos event log: when, which scenario, against what.
         */
        ChaosEvent: {
            /** Run Id */
            run_id: string;
            /**
             * At
             * Format: date-time
             */
            at: string;
            /** Scenario */
            scenario: string;
            /**
             * Action
             * @enum {string}
             */
            action: "apply" | "clear";
            /** Target */
            target: string;
            /** Interval Start */
            interval_start?: string | null;
            /**
             * Detail
             * @default
             */
            detail: string;
        };
        /** ClearChaosRequest */
        ClearChaosRequest: {
            /**
             * Scenario
             * @enum {string}
             */
            scenario: "worker-kill" | "duplicate-commands" | "partition" | "telemetry-delay";
            /** Run Id */
            run_id: string;
            /**
             * Target
             * @default simulators
             */
            target: string;
        };
        /** DependencyStatus */
        DependencyStatus: {
            /** Name */
            name: string;
            /** Ok */
            ok: boolean;
            /**
             * Detail
             * @default
             */
            detail: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Ok */
            ok: boolean;
            /** Dependencies */
            dependencies: components["schemas"]["DependencyStatus"][];
            /** Services */
            services: components["schemas"]["ServiceCount"][];
        };
        /** IntervalResult */
        IntervalResult: {
            /** Run Id */
            run_id: string;
            /**
             * Interval Start
             * Format: date-time
             */
            interval_start: string;
            /** Settlement Point */
            settlement_point: string;
            /** Price Usd Per Mwh */
            price_usd_per_mwh: number;
            /** Target Mw */
            target_mw: number;
            /** Achievable Mw */
            achievable_mw: number;
            /** Delivered Mw */
            delivered_mw: number;
            /** Level */
            level: string;
            /** Dispatched Count */
            dispatched_count: number;
            /** Acked Count */
            acked_count: number;
            /** Reserve Violations */
            reserve_violations: number;
            /** Latency Ms */
            latency_ms: number;
            /**
             * Budget Ms
             * @default 0
             */
            budget_ms: number;
            /**
             * Online Devices
             * @default 0
             */
            online_devices: number;
            /**
             * Shard Count
             * @default 0
             */
            shard_count: number;
            /**
             * Soc P10 Pct
             * @default 0
             */
            soc_p10_pct: number;
            /**
             * Soc P50 Pct
             * @default 0
             */
            soc_p50_pct: number;
            /**
             * Soc P90 Pct
             * @default 0
             */
            soc_p90_pct: number;
            /**
             * Duplicate Deliveries
             * @default 0
             */
            duplicate_deliveries: number;
            /**
             * Duplicate Effects
             * @default 0
             */
            duplicate_effects: number;
            /**
             * Retried Dispatches
             * @default 0
             */
            retried_dispatches: number;
            /**
             * Planned Achievable Mw
             * @default 0
             */
            planned_achievable_mw: number;
            /**
             * Stale Devices
             * @default 0
             */
            stale_devices: number;
            /**
             * Unresponsive Devices
             * @default 0
             */
            unresponsive_devices: number;
            /**
             * Reallocation Rounds
             * @default 0
             */
            reallocation_rounds: number;
            /**
             * Reallocated Mw
             * @default 0
             */
            reallocated_mw: number;
            /**
             * Reallocated Devices
             * @default 0
             */
            reallocated_devices: number;
        };
        /** LatestRun */
        LatestRun: {
            /** Run Id */
            run_id: string | null;
        };
        /**
         * LedgerIntervalSummary
         * @description The Command Ledger for one Market Interval: every Command issued, by status.
         */
        LedgerIntervalSummary: {
            /**
             * Interval Start
             * Format: date-time
             */
            interval_start: string;
            /** Issued */
            issued: number;
            /** Acked */
            acked: number;
            /** Expired */
            expired: number;
            /** Failed */
            failed: number;
            /** Unacked */
            unacked: number;
            /** Delivered Mw */
            delivered_mw: number;
        };
        /** PricePoint */
        PricePoint: {
            /**
             * Interval Start
             * Format: date-time
             */
            interval_start: string;
            /** Rt Price Usd Per Mwh */
            rt_price_usd_per_mwh: number | null;
            /** Dam Price Usd Per Mwh */
            dam_price_usd_per_mwh: number | null;
        };
        /** RecoveryTime */
        RecoveryTime: {
            /**
             * At
             * Format: date-time
             */
            at: string;
            /** Scenario */
            scenario: string;
            /** Target */
            target: string;
            /**
             * Interval Start
             * Format: date-time
             */
            interval_start: string;
            /** Recovery S */
            recovery_s: number | null;
        };
        /** ServiceCount */
        ServiceCount: {
            /** Name */
            name: string;
            /** Ready */
            ready: number;
            /** Total */
            total: number;
        };
        /** SloReport */
        SloReport: {
            /** Run Id */
            run_id: string;
            /** Rows */
            rows: components["schemas"]["SloRow"][];
            /** Recoveries */
            recoveries: components["schemas"]["RecoveryTime"][];
        };
        /** SloRow */
        SloRow: {
            /** Name */
            name: string;
            /** Target */
            target: string;
            /** Actual */
            actual: string;
            /** Ok */
            ok: boolean;
        };
        /** StartRunRequest */
        StartRunRequest: {
            /** Day */
            day?: string | null;
            /** Settlement Point */
            settlement_point?: string | null;
        };
        /** StartedRun */
        StartedRun: {
            /** Run Id */
            run_id: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    start_run_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StartedRun"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_latest_run_runs_latest_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LatestRun"];
                };
            };
        };
    };
    get_results_runs__run_id__results_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntervalResult"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ledger_runs__run_id__ledger_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LedgerIntervalSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_events_runs__run_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_cached_days_marketdata_days_get: {
        parameters: {
            query?: {
                settlement_point?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CachedDay"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_prices_marketdata_prices_get: {
        parameters: {
            query: {
                day: string;
                settlement_point?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PricePoint"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    apply_chaos_chaos_apply_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplyChaosRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChaosEvent"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clear_chaos_chaos_clear_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClearChaosRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChaosEvent"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_chaos_events_runs__run_id__chaos_events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChaosEvent"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_slo_runs__run_id__slo_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SloReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
