"""BENCHMARKS.md from a bench report (the dict `make bench` also saves as bench.json)."""

from gridtwin.bench.stats import SizeResult


def _ms(value: float | None) -> str:
    return "n/a" if value is None else f"{value:,.0f} ms"


def _size_row(r: SizeResult) -> str:
    verdict = "yes" if r.sustained else f"**no**{': ' + r.error[:80] if r.error else ''}"
    recovery = "n/a" if r.recovery_s is None else f"{r.recovery_s:.1f} s"
    return (
        f"| {r.devices:,} | {r.shards} / {r.simulators} | {r.completed}/{r.intervals} "
        f"| {_ms(r.p50_ms)} | {_ms(r.p99_ms)} | {_ms(r.max_ms)} | {_ms(r.budget_ms)} "
        f"| {r.commands_per_s:,.0f}/s | {recovery} | {_ms(r.kill_interval_ms)} "
        f"| {r.min_online_devices:,} | {r.fleet_state_mb:.2f} MB | {verdict} |"
    )


SIZE_HEADER = (
    "| Devices | Shards / simulators | Intervals done | p50 latency | p99 latency "
    "| Max latency | Wall budget | Commands/s | Recovery Time | Killed interval latency "
    "| Min online devices | Fleet State payload | Within budget |\n"
    "|---|---|---|---|---|---|---|---|---|---|---|---|---|"
)


def render_markdown(report: dict) -> str:
    sizes = [SizeResult.model_validate(r) for r in report["sizes"]]
    probes = [SizeResult.model_validate(r) for r in report["probes"]]
    soak = report["soak"]
    soak_run = SizeResult.model_validate(soak["run"])
    machine = report["machine"]
    config = report["config"]
    speed = report["replay_speed"]
    sustainable = report["max_sustainable_devices"]
    largest = max(r.devices for r in sizes)

    lines = [
        "# GridTwin benchmarks",
        "",
        f"Generated by `make bench` at {report['generated_at']} (UTC). Replay speed "
        f"{speed:g}x, so every Market Interval has a wall budget of "
        f"{900 / speed:g} s.",
        "",
        "## Headline",
        "",
    ]
    if sustainable >= largest:
        lines.append(
            f"- Every interval finished inside its wall budget at every size up to "
            f"**{largest:,} devices**."
        )
    else:
        lines.append(
            f"- **Maximum sustainable fleet: {sustainable:,} devices** at {speed:g}x "
            f"(largest size tried: {largest:,}). See *Where it breaks* below."
        )
    soak_line = f"- Memory over a {soak['minutes']:g}-minute soak at {soak['devices']:,} devices: "
    if soak["verdicts"] and all(v["flat"] for v in soak["verdicts"]):
        soak_line += (
            f"**flat** (every process within {config['memory_max_growth_pct']:g}% of its "
            "post-warm-up size)."
        )
    else:
        soak_line += "**not flat** (see the soak table)."
    lines.append(soak_line)
    recoveries = [r.recovery_s for r in sizes if r.recovery_s is not None]
    if recoveries:
        lines.append(
            f"- Recovery Time after a worker kill mid-dispatch: {min(recoveries):.1f}–"
            f"{max(recoveries):.1f} s across sizes (SLO 15 s)."
        )
    lines += [
        "",
        "## Matrix",
        "",
        SIZE_HEADER,
        *(_size_row(r) for r in sizes),
        "",
    ]
    if probes:
        lines += [
            "### Bisection probes (no worker kill)",
            "",
            SIZE_HEADER,
            *(_size_row(r) for r in probes),
            "",
        ]
    lines += [
        "### Planner solve time (LP, 96-interval horizon)",
        "",
        "| Devices | p50 | p99 |",
        "|---|---|---|",
        *(
            f"| {int(devices):,} | {p50:.1f} ms | {p99:.1f} ms |"
            for devices, (p50, p99) in report["planner_ms"].items()
        ),
        "",
        f"### Memory soak: {soak['devices']:,} devices, {soak['minutes']:g} minutes",
        "",
        f"{soak_run.completed} intervals replayed back to back on the same processes; "
        f"p50 {_ms(soak_run.p50_ms)}, p99 {_ms(soak_run.p99_ms)}, max {_ms(soak_run.max_ms)}"
        + (f"; error: {soak_run.error}" if soak_run.error else "")
        + ".",
        "",
        "| Process | RSS after warm-up | RSS at end | Max RSS | Growth | Flat |",
        "|---|---|---|---|---|---|",
        *(
            f"| {v['process']} | {v['warm_mb']:,.0f} MB | {v['end_mb']:,.0f} MB "
            f"| {v['max_mb']:,.0f} MB | {v['growth_pct']:+.1f}% | {'yes' if v['flat'] else 'no'} |"
            for v in soak["verdicts"]
        ),
        "",
        "## Machine",
        "",
        *(f"- **{key}**: {value}" for key, value in machine.items()),
        "",
        "## Configuration",
        "",
        *(f"- `{key}` = {value}" for key, value in config.items()),
        "",
    ]
    lines += METHODOLOGY
    return "\n".join(lines) + "\n"


METHODOLOGY = [
    "## Methodology",
    "",
    "- **Topology.** `make bench` starts its own Postgres, NATS and Temporal "
    "(`docker-compose.bench.yml`, project `gridtwin-bench`, separate ports) so it never "
    "shares a task queue or NATS subjects with the demo stack. For each fleet size it "
    "starts fresh host processes: two workers on the `gridtwin-bench` task queue, the "
    "telemetry ingester, and one simulator per `BENCH_SHARDS_PER_SIMULATOR` Shards (at "
    "least two). Shards scale with the fleet: `BENCH_DEVICES_PER_SHARD` Devices each, "
    "which is also the Command batch size. Strategy `naive`, the checked-in fixture day.",
    "- **Latency.** Each size replays `BENCH_INTERVALS` Market Intervals at "
    "`REPLAY_SPEED`. Latency is the Interval Result's `latency_ms`: Temporal time from the "
    "interval workflow's start to its result (feed read, Fleet State, plan, every Shard's "
    "dispatch, Reallocation). p50/p99 are nearest-rank over the intervals the worker kill "
    "did not hit; with fewer than 100 intervals p99 is the maximum. The killed interval is "
    "reported on its own.",
    "- **Within budget.** A size holds when every interval is replayed, each finishes "
    "inside its wall budget (900 s / speed), no run fails, and no Device drops out of "
    "Fleet State. When a size does not hold, the bench bisects between the largest size "
    "that did and the smallest that did not (`BENCH_PROBE_RESOLUTION`, "
    "`BENCH_PROBE_INTERVALS`, no kill) and reports the maximum sustainable device count.",
    "- **Commands/s.** Commands dispatched divided by the time spent dispatching (the sum "
    "of interval latencies), i.e. throughput while an interval is in flight, not averaged "
    "over the idle rest of the budget.",
    "- **Recovery Time.** After `BENCH_KILL_AT_INTERVAL` Interval Results, the bench "
    "polls Temporal for a `dispatch_shard` activity in flight (the chaos controller's "
    "probe), kills the worker process running it (TerminateProcess/SIGKILL, whole "
    "process tree), and polls the ledger every 50 ms until the interrupted interval's "
    "Interval Result exists. The worker is restarted after `CHAOS_RESTART_DELAY_SECONDS`.",
    "- **Planner.** In-process: the LP (`lp` Strategy) on a Fleet State of each size "
    "over the fixture day's prices as a 96-interval forecast, rotated per solve; "
    "20 solves, p50/p99.",
    "- **Memory.** The resident set size of every bench process (process tree) sampled "
    "every `BENCH_MEMORY_SAMPLE_SECONDS` over a `BENCH_SOAK_MINUTES` soak at the largest "
    "sustainable size, Replay Runs back to back on the same processes. Flat = the end "
    "sample is within `BENCH_MEMORY_MAX_GROWTH_PCT` of the first sample after "
    "`BENCH_MEMORY_WARMUP_SECONDS`.",
    "- **Raw data.** `data/cache/bench/bench.json` (every sample) and one log per process "
    "under `data/cache/bench/<size tag>/`. Neither is committed.",
    "",
]
