"""The ledger's interface: idempotent upsert by Idempotency Key, plus results (CONTEXT.md).

`PostgresLedgerRepo` backs the real worker; `InMemoryLedgerRepo` backs the Scenario
Runner (Seam A) so tests need no Postgres container.
"""

from typing import Protocol

from gridtwin.fleet.models import Ack, Command, DeviceState
from gridtwin.ledger.models import IntervalResult


class LedgerRepo(Protocol):
    def seed_devices(self, run_id: str, devices: list[DeviceState]) -> None: ...
    def get_devices(self, run_id: str) -> list[DeviceState]: ...
    def upsert_command(self, command: Command) -> None: ...
    def record_ack(self, ack: Ack) -> None: ...
    def update_device_soc(self, run_id: str, device_id: str, soc_pct: float) -> None: ...
    def record_interval_result(self, result: IntervalResult) -> None: ...
    def list_interval_results(self, run_id: str) -> list[IntervalResult]: ...
    def command_counts(self, run_id: str) -> tuple[int, int]:
        """(total commands, acked commands) for this run."""
        ...

    def latest_run_id(self) -> str | None: ...
